spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/espiel_ci_cd
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true