name: CI

on:
  push:
    branches:
      - master
      - release-candidate
      - dev
  pull_request:
    branches:
      - master
      - release-candidate
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        cache: maven
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode package -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        cache: maven
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Tests
        run: mvn --batch-mode test